version: '3.8'

services:
  # --- SERVICIO DE BACKEND ---
  backend:
    build: ./backend 
    image: mi-backend-minecraft
    container_name: fashiontpark-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
    networks:
      - fashiontpark-network

  # --- SERVICIO DE FRONTEND ---
  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:4000
    image: mi-frontend-minecraft
    container_name: fashiontpark-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - fashiontpark-network

networks:
  fashiontpark-network:
    driver: bridge